vich_uploader:
    db_driver: orm

    mappings:
       # Mapping pour l'image des articles
        project_files:
            uri_prefix: /files
            upload_destination: "%kernel.project_dir%/public/files"
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            directory_namer: app.directory_namer.content
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true

    metadata:
        type: attribute
